"""initial schema

Revision ID: d748e43f1680
Revises: 
Create Date: 2026-09-11 10:38:18.953741
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'd748e43f1680'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('parent_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name=op.f('ck_categories_valid_status')),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_index('ix_categories_parent_status', 'categories', ['parent_id', 'status'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("role IN ('CUSTOMER','MERCHANT','ADMIN')", name=op.f('ck_users_valid_role')),
    sa.CheckConstraint("status IN ('ACTIVE','SUSPENDED','DISABLED')", name=op.f('ck_users_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_role_status', 'users', ['role', 'status'], unique=False)
    op.create_table('addresses',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('recipient_name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('province', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_addresses_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    op.create_index('ix_addresses_user', 'addresses', ['user_id', 'id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_action_created', 'audit_logs', ['action', 'created_at', 'id'], unique=False)
    op.create_index('ix_audit_actor_created', 'audit_logs', ['actor_user_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_audit_entity_created', 'audit_logs', ['entity_type', 'entity_id', 'created_at', 'id'], unique=False)
    op.create_table('merchants',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('business_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('approved_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','ACTIVE','SUSPENDED','CLOSED')", name=op.f('ck_merchants_valid_status')),
    sa.CheckConstraint('(approved_at IS NULL AND approved_by IS NULL) OR (approved_at IS NOT NULL AND approved_by IS NOT NULL)', name=op.f('ck_merchants_approval_fields_together')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_merchants_approved_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_merchants_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants')),
    sa.UniqueConstraint('user_id', name=op.f('uq_merchants_user_id'))
    )
    op.create_index('ix_merchants_status_created', 'merchants', ['status', 'created_at'], unique=False)
    op.create_table('stores',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('merchant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','SUSPENDED','CLOSED')", name=op.f('ck_stores_valid_status')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_stores_merchant_id_merchants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores')),
    sa.UniqueConstraint('merchant_id', name=op.f('uq_stores_merchant_id'))
    )
    op.create_index('ix_stores_status', 'stores', ['status'], unique=False)
    op.create_table('carts',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('store_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('active_user_id', mysql.BIGINT(unsigned=True), sa.Computed("CASE WHEN status = 'ACTIVE' THEN user_id ELSE NULL END", persisted=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','CHECKED_OUT','ABANDONED')", name=op.f('ck_carts_valid_status')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_carts_store_id_stores'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_carts_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carts'))
    )
    op.create_index('ix_carts_user_created', 'carts', ['user_id', 'created_at', 'id'], unique=False)
    op.create_index('uq_carts_one_active_user', 'carts', ['active_user_id'], unique=True)
    op.create_table('orders',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('store_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('address_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('subtotal', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("payment_status IN ('UNPAID','PAID')", name=op.f('ck_orders_valid_payment_status')),
    sa.CheckConstraint("status IN ('PENDING_PAYMENT','PAID','PROCESSING','SHIPPED','COMPLETED','CANCELLED')", name=op.f('ck_orders_valid_status')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_orders_nonnegative_subtotal')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_orders_nonnegative_total')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_orders_store_id_stores'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('order_no', name=op.f('uq_orders_order_no'))
    )
    op.create_index('ix_orders_status_created', 'orders', ['status', 'created_at', 'id'], unique=False)
    op.create_index('ix_orders_store_status_created', 'orders', ['store_id', 'status', 'created_at', 'id'], unique=False)
    op.create_index('ix_orders_user_created', 'orders', ['user_id', 'created_at', 'id'], unique=False)
    op.create_table('products',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('store_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('category_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_price', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','ACTIVE','INACTIVE','DELETED')", name=op.f('ck_products_valid_status')),
    sa.CheckConstraint('current_price > 0', name=op.f('ck_products_positive_price')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_products_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index('ix_products_active_price', 'products', ['status', 'current_price', 'id'], unique=False)
    op.create_index('ix_products_browse', 'products', ['status', 'category_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_products_store_status', 'products', ['store_id', 'status', 'id'], unique=False)
    op.create_index('uq_products_store_sku', 'products', ['store_id', 'sku'], unique=True)
    op.create_table('cart_items',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('cart_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_cart_items_positive_quantity')),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_cart_items_cart_id_carts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_cart_items_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_items'))
    )
    op.create_index('ix_cart_items_product', 'cart_items', ['product_id'], unique=False)
    op.create_index('uq_cart_items_cart_product', 'cart_items', ['cart_id', 'product_id'], unique=True)
    op.create_table('inventory',
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('version', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_inventory_nonnegative_quantity')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_inventory'))
    )
    op.create_table('inventory_transactions',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.CheckConstraint("type IN ('RESTOCK','SALE','ADJUSTMENT','RETURN','RELEASE')", name=op.f('ck_inventory_transactions_valid_type')),
    sa.CheckConstraint('quantity_after >= 0', name=op.f('ck_inventory_transactions_nonnegative_after')),
    sa.CheckConstraint('quantity_before >= 0', name=op.f('ck_inventory_transactions_nonnegative_before')),
    sa.CheckConstraint('quantity_change <> 0', name=op.f('ck_inventory_transactions_nonzero_change')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_inventory_transactions_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_transactions_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_transactions'))
    )
    op.create_index('ix_inventory_tx_product_created', 'inventory_transactions', ['product_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_inventory_tx_reference', 'inventory_transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('store_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('product_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('sku_snapshot', sa.String(length=64), nullable=False),
    sa.Column('unit_price', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('subtotal', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_positive_quantity')),
    sa.CheckConstraint('subtotal > 0', name=op.f('ck_order_items_positive_subtotal')),
    sa.CheckConstraint('unit_price > 0', name=op.f('ck_order_items_positive_unit_price')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_order_items_store_id_stores'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index('ix_order_items_store_product', 'order_items', ['store_id', 'product_id'], unique=False)
    op.create_index('uq_order_items_order_product', 'order_items', ['order_id', 'product_id'], unique=True)
    op.create_table('payments',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('payment_no', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_order_id', mysql.BIGINT(unsigned=True), sa.Computed("CASE WHEN status = 'PAID' THEN order_id ELSE NULL END", persisted=True), nullable=True),
    sa.Column('paid_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("(status = 'PAID' AND paid_at IS NOT NULL) OR status <> 'PAID'", name=op.f('ck_payments_paid_at_required_when_paid')),
    sa.CheckConstraint("method IN ('MOCK_CARD','MOCK_WALLET')", name=op.f('ck_payments_valid_method')),
    sa.CheckConstraint("status IN ('PENDING','PAID','FAILED','REFUNDED')", name=op.f('ck_payments_valid_status')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_positive_amount')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('payment_no', name=op.f('uq_payments_payment_no'))
    )
    op.create_index('ix_payments_order_created', 'payments', ['order_id', 'created_at', 'id'], unique=False)
    op.create_index('uq_payments_one_paid_order', 'payments', ['paid_order_id'], unique=True)
    op.create_index('uq_payments_order_idempotency', 'payments', ['order_id', 'idempotency_key'], unique=True)
    op.create_table('product_prices',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('old_price', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('new_price', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('changed_by', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('changed_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.CheckConstraint('new_price > 0', name=op.f('ck_product_prices_positive_new_price')),
    sa.CheckConstraint('old_price <> new_price', name=op.f('ck_product_prices_prices_different')),
    sa.CheckConstraint('old_price > 0', name=op.f('ck_product_prices_positive_old_price')),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_product_prices_changed_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_prices_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_prices'))
    )
    op.create_index('ix_product_prices_product_changed', 'product_prices', ['product_id', 'changed_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Indexes are dropped with their tables. Dropping them first can fail on
    # MySQL when an index is also used to support a foreign key.
    op.drop_table('product_prices')
    op.drop_table('payments')
    op.drop_table('order_items')
    op.drop_table('inventory_transactions')
    op.drop_table('inventory')
    op.drop_table('cart_items')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('carts')
    op.drop_table('stores')
    op.drop_table('merchants')
    op.drop_table('audit_logs')
    op.drop_table('addresses')
    op.drop_table('users')
    op.drop_table('categories')
